// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: examplemixer.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on HelloReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *HelloReq) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetMessage()) < 1 {
		return HelloReqValidationError{
			field:  "Message",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// HelloReqValidationError is the validation error returned by
// HelloReq.Validate if the designated constraints aren't met.
type HelloReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloReqValidationError) ErrorName() string { return "HelloReqValidationError" }

// Error satisfies the builtin error interface
func (e HelloReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloReqValidationError{}
